<?php
/**
 * ResultschemaResultItem5Test
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BSG\Api\V1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BSG SMS Gateway API
 *
 * Comprehensive API for sending SMS, Viber messages, HLR/MNP requests and service management
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@bsg.world
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BSG\Api\V1\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ResultschemaResultItem5Test Class Doc Comment
 *
 * @category    Class
 * @description ResultschemaResultItem5
 * @package     BSG\Api\V1
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ResultschemaResultItem5Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ResultschemaResultItem5"
     */
    public function testResultschemaResultItem5()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "error_description"
     */
    public function testPropertyErrorDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "msisdn"
     */
    public function testPropertyMsisdn()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tariff_code"
     */
    public function testPropertyTariffCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "info"
     */
    public function testPropertyInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
