<?php
/**
 * ExportsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BSG\Api\V1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BSG SMS Gateway API
 *
 * Comprehensive API for sending SMS, Viber messages, HLR/MNP requests and service management
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@bsg.world
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BSG\Api\V1\Test\Api;

use \BSG\Api\V1\Configuration;
use \BSG\Api\V1\ApiException;
use \BSG\Api\V1\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ExportsApiTest Class Doc Comment
 *
 * @category Class
 * @package  BSG\Api\V1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ExportsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for exportsDeleteFile
     *
     * Delete export file.
     *
     */
    public function testExportsDeleteFile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for exportsGetFile
     *
     * Download export file.
     *
     */
    public function testExportsGetFile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for exportsGetList
     *
     * List export jobs.
     *
     */
    public function testExportsGetList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for exportsRequestExport
     *
     * Request data export.
     *
     */
    public function testExportsRequestExport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for exportsRequestExportPut
     *
     * Request data export (PUT).
     *
     */
    public function testExportsRequestExportPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
