<?php
/**
 * MNPApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BSG\Api\V1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BSG SMS Gateway API
 *
 * Comprehensive API for sending SMS, Viber messages, HLR/MNP requests and service management
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@bsg.world
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BSG\Api\V1\Test\Api;

use \BSG\Api\V1\Configuration;
use \BSG\Api\V1\ApiException;
use \BSG\Api\V1\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MNPApiTest Class Doc Comment
 *
 * @category Class
 * @package  BSG\Api\V1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MNPApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for mnpCreateBatchMnp
     *
     * MNP lookup for multiple numbers (JSON body).
     *
     */
    public function testMnpCreateBatchMnp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mnpCreateObjectsPut
     *
     * Perform MNP lookup (PUT).
     *
     */
    public function testMnpCreateObjectsPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mnpGetPrices
     *
     * Get MNP pricing.
     *
     */
    public function testMnpGetPrices()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mnpGetStatusByExtId
     *
     * Get MNP result by reference.
     *
     */
    public function testMnpGetStatusByExtId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mnpGetStatusById
     *
     * Get MNP result by ID.
     *
     */
    public function testMnpGetStatusById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
