<?php
/**
 * MessagesSMSApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BSG\\Api\\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * One-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BSG\\Api\\V2\Test\Api;

use \BSG\\Api\\V2\Configuration;
use \BSG\\Api\\V2\ApiException;
use \BSG\\Api\\V2\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MessagesSMSApiTest Class Doc Comment
 *
 * @category Class
 * @package  BSG\\Api\\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MessagesSMSApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for b696e239f742e868841bd2173294ef8e
     *
     * Find messages.
     *
     */
    public function testB696e239f742e868841bd2173294ef8e()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
