<?php
/**
 * SmsMultipleCreateRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BSG\Api\V1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BSG SMS Gateway API
 *
 * Comprehensive API for sending SMS, Viber messages, HLR/MNP requests and service management
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@bsg.world
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BSG\Api\V1\Model;

use \ArrayAccess;
use \BSG\Api\V1\ObjectSerializer;

/**
 * SmsMultipleCreateRequest Class Doc Comment
 *
 * @category Class
 * @package  BSG\Api\V1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SmsMultipleCreateRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SmsMultipleCreateRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'destination' => 'string',
        'phones' => '\BSG\Api\V1\Model\PhonenumbersPhonesItem[]',
        'reference' => 'string',
        'originator' => 'string',
        'body' => 'string',
        'callback_url' => 'string',
        'transliterate' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'destination' => null,
        'phones' => null,
        'reference' => null,
        'originator' => null,
        'body' => null,
        'callback_url' => 'uri',
        'transliterate' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'destination' => false,
        'phones' => false,
        'reference' => false,
        'originator' => false,
        'body' => false,
        'callback_url' => false,
        'transliterate' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'destination' => 'destination',
        'phones' => 'phones',
        'reference' => 'reference',
        'originator' => 'originator',
        'body' => 'body',
        'callback_url' => 'callback_url',
        'transliterate' => 'transliterate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'destination' => 'setDestination',
        'phones' => 'setPhones',
        'reference' => 'setReference',
        'originator' => 'setOriginator',
        'body' => 'setBody',
        'callback_url' => 'setCallbackUrl',
        'transliterate' => 'setTransliterate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'destination' => 'getDestination',
        'phones' => 'getPhones',
        'reference' => 'getReference',
        'originator' => 'getOriginator',
        'body' => 'getBody',
        'callback_url' => 'getCallbackUrl',
        'transliterate' => 'getTransliterate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const DESTINATION_PHONES = 'phones';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDestinationAllowableValues()
    {
        return [
            self::DESTINATION_PHONES,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('destination', $data ?? [], null);
        $this->setIfExists('phones', $data ?? [], null);
        $this->setIfExists('reference', $data ?? [], null);
        $this->setIfExists('originator', $data ?? [], null);
        $this->setIfExists('body', $data ?? [], null);
        $this->setIfExists('callback_url', $data ?? [], null);
        $this->setIfExists('transliterate', $data ?? [], false);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['destination'] === null) {
            $invalidProperties[] = "'destination' can't be null";
        }
        $allowedValues = $this->getDestinationAllowableValues();
        if (!is_null($this->container['destination']) && !in_array($this->container['destination'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'destination', must be one of '%s'",
                $this->container['destination'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['phones'] === null) {
            $invalidProperties[] = "'phones' can't be null";
        }
        if ((count($this->container['phones']) > 1000)) {
            $invalidProperties[] = "invalid value for 'phones', number of items must be less than or equal to 1000.";
        }

        if ((count($this->container['phones']) < 1)) {
            $invalidProperties[] = "invalid value for 'phones', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['reference']) && (mb_strlen($this->container['reference']) > 50)) {
            $invalidProperties[] = "invalid value for 'reference', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['reference']) && !preg_match("/^[a-zA-Z0-9_-]+$/", $this->container['reference'])) {
            $invalidProperties[] = "invalid value for 'reference', must be conform to the pattern /^[a-zA-Z0-9_-]+$/.";
        }

        if ($this->container['originator'] === null) {
            $invalidProperties[] = "'originator' can't be null";
        }
        if ((mb_strlen($this->container['originator']) > 15)) {
            $invalidProperties[] = "invalid value for 'originator', the character length must be smaller than or equal to 15.";
        }

        if ((mb_strlen($this->container['originator']) < 3)) {
            $invalidProperties[] = "invalid value for 'originator', the character length must be bigger than or equal to 3.";
        }

        if ($this->container['body'] === null) {
            $invalidProperties[] = "'body' can't be null";
        }
        if ((mb_strlen($this->container['body']) > 765)) {
            $invalidProperties[] = "invalid value for 'body', the character length must be smaller than or equal to 765.";
        }

        if ((mb_strlen($this->container['body']) < 1)) {
            $invalidProperties[] = "invalid value for 'body', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['callback_url']) && (mb_strlen($this->container['callback_url']) > 500)) {
            $invalidProperties[] = "invalid value for 'callback_url', the character length must be smaller than or equal to 500.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets destination
     *
     * @return string
     */
    public function getDestination()
    {
        return $this->container['destination'];
    }

    /**
     * Sets destination
     *
     * @param string $destination Message destination type for multiple recipients
     *
     * @return self
     */
    public function setDestination($destination)
    {
        if (is_null($destination)) {
            throw new \InvalidArgumentException('non-nullable destination cannot be null');
        }
        $allowedValues = $this->getDestinationAllowableValues();
        if (!in_array($destination, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'destination', must be one of '%s'",
                    $destination,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['destination'] = $destination;

        return $this;
    }

    /**
     * Gets phones
     *
     * @return \BSG\Api\V1\Model\PhonenumbersPhonesItem[]
     */
    public function getPhones()
    {
        return $this->container['phones'];
    }

    /**
     * Sets phones
     *
     * @param \BSG\Api\V1\Model\PhonenumbersPhonesItem[] $phones Array of phone objects (required for destination=phones). Maximum 1000 recipients per request
     *
     * @return self
     */
    public function setPhones($phones)
    {
        if (is_null($phones)) {
            throw new \InvalidArgumentException('non-nullable phones cannot be null');
        }

        if ((count($phones) > 1000)) {
            throw new \InvalidArgumentException('invalid value for $phones when calling SmsMultipleCreateRequest., number of items must be less than or equal to 1000.');
        }
        if ((count($phones) < 1)) {
            throw new \InvalidArgumentException('invalid length for $phones when calling SmsMultipleCreateRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['phones'] = $phones;

        return $this;
    }

    /**
     * Gets reference
     *
     * @return string|null
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     *
     * @param string|null $reference Global reference ID for entire batch
     *
     * @return self
     */
    public function setReference($reference)
    {
        if (is_null($reference)) {
            throw new \InvalidArgumentException('non-nullable reference cannot be null');
        }
        if ((mb_strlen($reference) > 50)) {
            throw new \InvalidArgumentException('invalid length for $reference when calling SmsMultipleCreateRequest., must be smaller than or equal to 50.');
        }
        if ((!preg_match("/^[a-zA-Z0-9_-]+$/", ObjectSerializer::toString($reference)))) {
            throw new \InvalidArgumentException("invalid value for \$reference when calling SmsMultipleCreateRequest., must conform to the pattern /^[a-zA-Z0-9_-]+$/.");
        }

        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets originator
     *
     * @return string
     */
    public function getOriginator()
    {
        return $this->container['originator'];
    }

    /**
     * Sets originator
     *
     * @param string $originator Sender name for all messages in batch
     *
     * @return self
     */
    public function setOriginator($originator)
    {
        if (is_null($originator)) {
            throw new \InvalidArgumentException('non-nullable originator cannot be null');
        }
        if ((mb_strlen($originator) > 15)) {
            throw new \InvalidArgumentException('invalid length for $originator when calling SmsMultipleCreateRequest., must be smaller than or equal to 15.');
        }
        if ((mb_strlen($originator) < 3)) {
            throw new \InvalidArgumentException('invalid length for $originator when calling SmsMultipleCreateRequest., must be bigger than or equal to 3.');
        }

        $this->container['originator'] = $originator;

        return $this;
    }

    /**
     * Gets body
     *
     * @return string
     */
    public function getBody()
    {
        return $this->container['body'];
    }

    /**
     * Sets body
     *
     * @param string $body SMS text content for all recipients
     *
     * @return self
     */
    public function setBody($body)
    {
        if (is_null($body)) {
            throw new \InvalidArgumentException('non-nullable body cannot be null');
        }
        if ((mb_strlen($body) > 765)) {
            throw new \InvalidArgumentException('invalid length for $body when calling SmsMultipleCreateRequest., must be smaller than or equal to 765.');
        }
        if ((mb_strlen($body) < 1)) {
            throw new \InvalidArgumentException('invalid length for $body when calling SmsMultipleCreateRequest., must be bigger than or equal to 1.');
        }

        $this->container['body'] = $body;

        return $this;
    }

    /**
     * Gets callback_url
     *
     * @return string|null
     */
    public function getCallbackUrl()
    {
        return $this->container['callback_url'];
    }

    /**
     * Sets callback_url
     *
     * @param string|null $callback_url HTTPS URL for receiving delivery reports
     *
     * @return self
     */
    public function setCallbackUrl($callback_url)
    {
        if (is_null($callback_url)) {
            throw new \InvalidArgumentException('non-nullable callback_url cannot be null');
        }
        if ((mb_strlen($callback_url) > 500)) {
            throw new \InvalidArgumentException('invalid length for $callback_url when calling SmsMultipleCreateRequest., must be smaller than or equal to 500.');
        }

        $this->container['callback_url'] = $callback_url;

        return $this;
    }

    /**
     * Gets transliterate
     *
     * @return bool|null
     */
    public function getTransliterate()
    {
        return $this->container['transliterate'];
    }

    /**
     * Sets transliterate
     *
     * @param bool|null $transliterate Apply transliteration to SMS text. Converts Cyrillic characters to Latin equivalents to reduce message cost and ensure delivery
     *
     * @return self
     */
    public function setTransliterate($transliterate)
    {
        if (is_null($transliterate)) {
            throw new \InvalidArgumentException('non-nullable transliterate cannot be null');
        }
        $this->container['transliterate'] = $transliterate;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


