<?php
/**
 * SmsSingleCreateRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BSG\Api\V1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BSG SMS Gateway API
 *
 * Comprehensive API for sending SMS, Viber messages, HLR/MNP requests and service management
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@bsg.world
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BSG\Api\V1\Model;

use \ArrayAccess;
use \BSG\Api\V1\ObjectSerializer;

/**
 * SmsSingleCreateRequest Class Doc Comment
 *
 * @category Class
 * @package  BSG\Api\V1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SmsSingleCreateRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SmsSingleCreateRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'destination' => 'string',
        'msisdn' => 'string',
        'reference' => 'string',
        'originator' => 'string',
        'body' => 'string',
        'callback_url' => 'string',
        'callback_url_2way' => 'string',
        'transliterate' => 'bool',
        '_2way' => 'bool',
        'tariff' => 'int',
        'scheduled_datetime' => '\DateTime',
        'data_coding_ucs2' => 'bool',
        'validity' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'destination' => null,
        'msisdn' => null,
        'reference' => null,
        'originator' => null,
        'body' => null,
        'callback_url' => 'uri',
        'callback_url_2way' => 'uri',
        'transliterate' => null,
        '_2way' => null,
        'tariff' => null,
        'scheduled_datetime' => 'date-time',
        'data_coding_ucs2' => null,
        'validity' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'destination' => false,
        'msisdn' => false,
        'reference' => false,
        'originator' => false,
        'body' => false,
        'callback_url' => false,
        'callback_url_2way' => false,
        'transliterate' => false,
        '_2way' => false,
        'tariff' => false,
        'scheduled_datetime' => false,
        'data_coding_ucs2' => false,
        'validity' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'destination' => 'destination',
        'msisdn' => 'msisdn',
        'reference' => 'reference',
        'originator' => 'originator',
        'body' => 'body',
        'callback_url' => 'callback_url',
        'callback_url_2way' => 'callback_url_2way',
        'transliterate' => 'transliterate',
        '_2way' => '2way',
        'tariff' => 'tariff',
        'scheduled_datetime' => 'scheduledDatetime',
        'data_coding_ucs2' => 'data_coding_ucs2',
        'validity' => 'validity'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'destination' => 'setDestination',
        'msisdn' => 'setMsisdn',
        'reference' => 'setReference',
        'originator' => 'setOriginator',
        'body' => 'setBody',
        'callback_url' => 'setCallbackUrl',
        'callback_url_2way' => 'setCallbackUrl2way',
        'transliterate' => 'setTransliterate',
        '_2way' => 'set2way',
        'tariff' => 'setTariff',
        'scheduled_datetime' => 'setScheduledDatetime',
        'data_coding_ucs2' => 'setDataCodingUcs2',
        'validity' => 'setValidity'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'destination' => 'getDestination',
        'msisdn' => 'getMsisdn',
        'reference' => 'getReference',
        'originator' => 'getOriginator',
        'body' => 'getBody',
        'callback_url' => 'getCallbackUrl',
        'callback_url_2way' => 'getCallbackUrl2way',
        'transliterate' => 'getTransliterate',
        '_2way' => 'get2way',
        'tariff' => 'getTariff',
        'scheduled_datetime' => 'getScheduledDatetime',
        'data_coding_ucs2' => 'getDataCodingUcs2',
        'validity' => 'getValidity'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const DESTINATION_PHONE = 'phone';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDestinationAllowableValues()
    {
        return [
            self::DESTINATION_PHONE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('destination', $data ?? [], null);
        $this->setIfExists('msisdn', $data ?? [], null);
        $this->setIfExists('reference', $data ?? [], null);
        $this->setIfExists('originator', $data ?? [], null);
        $this->setIfExists('body', $data ?? [], null);
        $this->setIfExists('callback_url', $data ?? [], null);
        $this->setIfExists('callback_url_2way', $data ?? [], null);
        $this->setIfExists('transliterate', $data ?? [], false);
        $this->setIfExists('_2way', $data ?? [], false);
        $this->setIfExists('tariff', $data ?? [], null);
        $this->setIfExists('scheduled_datetime', $data ?? [], null);
        $this->setIfExists('data_coding_ucs2', $data ?? [], false);
        $this->setIfExists('validity', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['destination'] === null) {
            $invalidProperties[] = "'destination' can't be null";
        }
        $allowedValues = $this->getDestinationAllowableValues();
        if (!is_null($this->container['destination']) && !in_array($this->container['destination'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'destination', must be one of '%s'",
                $this->container['destination'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['msisdn'] === null) {
            $invalidProperties[] = "'msisdn' can't be null";
        }
        if ((mb_strlen($this->container['msisdn']) > 15)) {
            $invalidProperties[] = "invalid value for 'msisdn', the character length must be smaller than or equal to 15.";
        }

        if ((mb_strlen($this->container['msisdn']) < 8)) {
            $invalidProperties[] = "invalid value for 'msisdn', the character length must be bigger than or equal to 8.";
        }

        if (!preg_match("/^[1-9][0-9]{7,14}$/", $this->container['msisdn'])) {
            $invalidProperties[] = "invalid value for 'msisdn', must be conform to the pattern /^[1-9][0-9]{7,14}$/.";
        }

        if (!is_null($this->container['reference']) && (mb_strlen($this->container['reference']) > 50)) {
            $invalidProperties[] = "invalid value for 'reference', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['reference']) && !preg_match("/^[a-zA-Z0-9_-]+$/", $this->container['reference'])) {
            $invalidProperties[] = "invalid value for 'reference', must be conform to the pattern /^[a-zA-Z0-9_-]+$/.";
        }

        if ($this->container['originator'] === null) {
            $invalidProperties[] = "'originator' can't be null";
        }
        if ((mb_strlen($this->container['originator']) > 15)) {
            $invalidProperties[] = "invalid value for 'originator', the character length must be smaller than or equal to 15.";
        }

        if ((mb_strlen($this->container['originator']) < 3)) {
            $invalidProperties[] = "invalid value for 'originator', the character length must be bigger than or equal to 3.";
        }

        if ($this->container['body'] === null) {
            $invalidProperties[] = "'body' can't be null";
        }
        if ((mb_strlen($this->container['body']) > 765)) {
            $invalidProperties[] = "invalid value for 'body', the character length must be smaller than or equal to 765.";
        }

        if ((mb_strlen($this->container['body']) < 1)) {
            $invalidProperties[] = "invalid value for 'body', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['callback_url']) && (mb_strlen($this->container['callback_url']) > 500)) {
            $invalidProperties[] = "invalid value for 'callback_url', the character length must be smaller than or equal to 500.";
        }

        if (!is_null($this->container['callback_url_2way']) && (mb_strlen($this->container['callback_url_2way']) > 500)) {
            $invalidProperties[] = "invalid value for 'callback_url_2way', the character length must be smaller than or equal to 500.";
        }

        if (!is_null($this->container['tariff']) && ($this->container['tariff'] > 999)) {
            $invalidProperties[] = "invalid value for 'tariff', must be smaller than or equal to 999.";
        }

        if (!is_null($this->container['tariff']) && ($this->container['tariff'] < 1)) {
            $invalidProperties[] = "invalid value for 'tariff', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['scheduled_datetime']) && !preg_match("/^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$/", $this->container['scheduled_datetime'])) {
            $invalidProperties[] = "invalid value for 'scheduled_datetime', must be conform to the pattern /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$/.";
        }

        if (!is_null($this->container['validity']) && ($this->container['validity'] > 87840)) {
            $invalidProperties[] = "invalid value for 'validity', must be smaller than or equal to 87840.";
        }

        if (!is_null($this->container['validity']) && ($this->container['validity'] < 1)) {
            $invalidProperties[] = "invalid value for 'validity', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets destination
     *
     * @return string
     */
    public function getDestination()
    {
        return $this->container['destination'];
    }

    /**
     * Sets destination
     *
     * @param string $destination Message destination type for single recipient
     *
     * @return self
     */
    public function setDestination($destination)
    {
        if (is_null($destination)) {
            throw new \InvalidArgumentException('non-nullable destination cannot be null');
        }
        $allowedValues = $this->getDestinationAllowableValues();
        if (!in_array($destination, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'destination', must be one of '%s'",
                    $destination,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['destination'] = $destination;

        return $this;
    }

    /**
     * Gets msisdn
     *
     * @return string
     */
    public function getMsisdn()
    {
        return $this->container['msisdn'];
    }

    /**
     * Sets msisdn
     *
     * @param string $msisdn Phone number in international format without + sign. Required for destination=phone/otp. Must be 8-15 digits starting with country code
     *
     * @return self
     */
    public function setMsisdn($msisdn)
    {
        if (is_null($msisdn)) {
            throw new \InvalidArgumentException('non-nullable msisdn cannot be null');
        }
        if ((mb_strlen($msisdn) > 15)) {
            throw new \InvalidArgumentException('invalid length for $msisdn when calling SmsSingleCreateRequest., must be smaller than or equal to 15.');
        }
        if ((mb_strlen($msisdn) < 8)) {
            throw new \InvalidArgumentException('invalid length for $msisdn when calling SmsSingleCreateRequest., must be bigger than or equal to 8.');
        }
        if ((!preg_match("/^[1-9][0-9]{7,14}$/", ObjectSerializer::toString($msisdn)))) {
            throw new \InvalidArgumentException("invalid value for \$msisdn when calling SmsSingleCreateRequest., must conform to the pattern /^[1-9][0-9]{7,14}$/.");
        }

        $this->container['msisdn'] = $msisdn;

        return $this;
    }

    /**
     * Gets reference
     *
     * @return string|null
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     *
     * @param string|null $reference External reference ID for tracking message. Must be unique. Auto-generated if not provided. Only alphanumeric characters, hyphens and underscores allowed
     *
     * @return self
     */
    public function setReference($reference)
    {
        if (is_null($reference)) {
            throw new \InvalidArgumentException('non-nullable reference cannot be null');
        }
        if ((mb_strlen($reference) > 50)) {
            throw new \InvalidArgumentException('invalid length for $reference when calling SmsSingleCreateRequest., must be smaller than or equal to 50.');
        }
        if ((!preg_match("/^[a-zA-Z0-9_-]+$/", ObjectSerializer::toString($reference)))) {
            throw new \InvalidArgumentException("invalid value for \$reference when calling SmsSingleCreateRequest., must conform to the pattern /^[a-zA-Z0-9_-]+$/.");
        }

        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets originator
     *
     * @return string
     */
    public function getOriginator()
    {
        return $this->container['originator'];
    }

    /**
     * Sets originator
     *
     * @param string $originator Sender's name: from 3 to 11 characters for alphanumeric name (Latin letters, symbols, numbers, spaces); 3 to 15 characters for numeric name. Required field
     *
     * @return self
     */
    public function setOriginator($originator)
    {
        if (is_null($originator)) {
            throw new \InvalidArgumentException('non-nullable originator cannot be null');
        }
        if ((mb_strlen($originator) > 15)) {
            throw new \InvalidArgumentException('invalid length for $originator when calling SmsSingleCreateRequest., must be smaller than or equal to 15.');
        }
        if ((mb_strlen($originator) < 3)) {
            throw new \InvalidArgumentException('invalid length for $originator when calling SmsSingleCreateRequest., must be bigger than or equal to 3.');
        }

        $this->container['originator'] = $originator;

        return $this;
    }

    /**
     * Gets body
     *
     * @return string
     */
    public function getBody()
    {
        return $this->container['body'];
    }

    /**
     * Sets body
     *
     * @param string $body SMS text content. Maximum length is 765 characters for GSM 7-bit encoding (Latin), and 355 characters for UCS-2 (Unicode). Required field
     *
     * @return self
     */
    public function setBody($body)
    {
        if (is_null($body)) {
            throw new \InvalidArgumentException('non-nullable body cannot be null');
        }
        if ((mb_strlen($body) > 765)) {
            throw new \InvalidArgumentException('invalid length for $body when calling SmsSingleCreateRequest., must be smaller than or equal to 765.');
        }
        if ((mb_strlen($body) < 1)) {
            throw new \InvalidArgumentException('invalid length for $body when calling SmsSingleCreateRequest., must be bigger than or equal to 1.');
        }

        $this->container['body'] = $body;

        return $this;
    }

    /**
     * Gets callback_url
     *
     * @return string|null
     */
    public function getCallbackUrl()
    {
        return $this->container['callback_url'];
    }

    /**
     * Sets callback_url
     *
     * @param string|null $callback_url HTTPS URL for receiving delivery reports (DLR). Must be accessible from our servers. We will POST delivery status updates to this endpoint
     *
     * @return self
     */
    public function setCallbackUrl($callback_url)
    {
        if (is_null($callback_url)) {
            throw new \InvalidArgumentException('non-nullable callback_url cannot be null');
        }
        if ((mb_strlen($callback_url) > 500)) {
            throw new \InvalidArgumentException('invalid length for $callback_url when calling SmsSingleCreateRequest., must be smaller than or equal to 500.');
        }

        $this->container['callback_url'] = $callback_url;

        return $this;
    }

    /**
     * Gets callback_url_2way
     *
     * @return string|null
     */
    public function getCallbackUrl2way()
    {
        return $this->container['callback_url_2way'];
    }

    /**
     * Sets callback_url_2way
     *
     * @param string|null $callback_url_2way HTTPS URL for receiving 2-way SMS responses. Only works if 2way=true and sender supports incoming messages
     *
     * @return self
     */
    public function setCallbackUrl2way($callback_url_2way)
    {
        if (is_null($callback_url_2way)) {
            throw new \InvalidArgumentException('non-nullable callback_url_2way cannot be null');
        }
        if ((mb_strlen($callback_url_2way) > 500)) {
            throw new \InvalidArgumentException('invalid length for $callback_url_2way when calling SmsSingleCreateRequest., must be smaller than or equal to 500.');
        }

        $this->container['callback_url_2way'] = $callback_url_2way;

        return $this;
    }

    /**
     * Gets transliterate
     *
     * @return bool|null
     */
    public function getTransliterate()
    {
        return $this->container['transliterate'];
    }

    /**
     * Sets transliterate
     *
     * @param bool|null $transliterate Apply transliteration to SMS text if necessary. Converts Cyrillic characters to Latin equivalents to reduce message cost and ensure delivery
     *
     * @return self
     */
    public function setTransliterate($transliterate)
    {
        if (is_null($transliterate)) {
            throw new \InvalidArgumentException('non-nullable transliterate cannot be null');
        }
        $this->container['transliterate'] = $transliterate;

        return $this;
    }

    /**
     * Gets _2way
     *
     * @return bool|null
     */
    public function get2way()
    {
        return $this->container['_2way'];
    }

    /**
     * Sets _2way
     *
     * @param bool|null $_2way Enable two-way SMS communication. Allows recipients to reply to your message. Requires callback_url_2way for receiving replies
     *
     * @return self
     */
    public function set2way($_2way)
    {
        if (is_null($_2way)) {
            throw new \InvalidArgumentException('non-nullable _2way cannot be null');
        }
        $this->container['_2way'] = $_2way;

        return $this;
    }

    /**
     * Gets tariff
     *
     * @return int|null
     */
    public function getTariff()
    {
        return $this->container['tariff'];
    }

    /**
     * Sets tariff
     *
     * @param int|null $tariff Specific tariff code to use for pricing this message. Optional - uses user's default tariff if not specified. Must be a valid tariff code available to your account
     *
     * @return self
     */
    public function setTariff($tariff)
    {
        if (is_null($tariff)) {
            throw new \InvalidArgumentException('non-nullable tariff cannot be null');
        }

        if (($tariff > 999)) {
            throw new \InvalidArgumentException('invalid value for $tariff when calling SmsSingleCreateRequest., must be smaller than or equal to 999.');
        }
        if (($tariff < 1)) {
            throw new \InvalidArgumentException('invalid value for $tariff when calling SmsSingleCreateRequest., must be bigger than or equal to 1.');
        }

        $this->container['tariff'] = $tariff;

        return $this;
    }

    /**
     * Gets scheduled_datetime
     *
     * @return \DateTime|null
     */
    public function getScheduledDatetime()
    {
        return $this->container['scheduled_datetime'];
    }

    /**
     * Sets scheduled_datetime
     *
     * @param \DateTime|null $scheduled_datetime Schedule message delivery for future time. Must be in UTC format (ISO 8601). Example: 2024-12-25T10:30:00Z. If not specified, message is sent immediately
     *
     * @return self
     */
    public function setScheduledDatetime($scheduled_datetime)
    {
        if (is_null($scheduled_datetime)) {
            throw new \InvalidArgumentException('non-nullable scheduled_datetime cannot be null');
        }

        if ((!preg_match("/^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$/", ObjectSerializer::toString($scheduled_datetime)))) {
            throw new \InvalidArgumentException("invalid value for \$scheduled_datetime when calling SmsSingleCreateRequest., must conform to the pattern /^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$/.");
        }

        $this->container['scheduled_datetime'] = $scheduled_datetime;

        return $this;
    }

    /**
     * Gets data_coding_ucs2
     *
     * @return bool|null
     */
    public function getDataCodingUcs2()
    {
        return $this->container['data_coding_ucs2'];
    }

    /**
     * Sets data_coding_ucs2
     *
     * @param bool|null $data_coding_ucs2 Force UCS-2 (Unicode) encoding for message text. Useful for non-Latin characters (Cyrillic, Arabic, Chinese, etc). Reduces max message length to 355 characters
     *
     * @return self
     */
    public function setDataCodingUcs2($data_coding_ucs2)
    {
        if (is_null($data_coding_ucs2)) {
            throw new \InvalidArgumentException('non-nullable data_coding_ucs2 cannot be null');
        }
        $this->container['data_coding_ucs2'] = $data_coding_ucs2;

        return $this;
    }

    /**
     * Gets validity
     *
     * @return int|null
     */
    public function getValidity()
    {
        return $this->container['validity'];
    }

    /**
     * Sets validity
     *
     * @param int|null $validity Message validity period in hours. Default is 72 hours (3 days). Maximum is 87840 hours (10 years). After this time, undelivered message will expire
     *
     * @return self
     */
    public function setValidity($validity)
    {
        if (is_null($validity)) {
            throw new \InvalidArgumentException('non-nullable validity cannot be null');
        }

        if (($validity > 87840)) {
            throw new \InvalidArgumentException('invalid value for $validity when calling SmsSingleCreateRequest., must be smaller than or equal to 87840.');
        }
        if (($validity < 1)) {
            throw new \InvalidArgumentException('invalid value for $validity when calling SmsSingleCreateRequest., must be bigger than or equal to 1.');
        }

        $this->container['validity'] = $validity;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


