<?php
/**
 * FilteridsThisCollectionShouldContain3ElementsOrLessErrorsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BSG\Api\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * One-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BSG\Api\V2\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FilteridsThisCollectionShouldContain3ElementsOrLessErrorsTest Class Doc Comment
 *
 * @category    Class
 * @description FilteridsThisCollectionShouldContain3ElementsOrLessErrors
 * @package     BSG\Api\V2
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FilteridsThisCollectionShouldContain3ElementsOrLessErrorsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FilteridsThisCollectionShouldContain3ElementsOrLessErrors"
     */
    public function testFilteridsThisCollectionShouldContain3ElementsOrLessErrors()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "filter_ids"
     */
    public function testPropertyFilterIds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
