<?php
/**
 * ContactFieldType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BSG\Api\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * One-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BSG\Api\V2\Model;
use \BSG\Api\V2\ObjectSerializer;

/**
 * ContactFieldType Class Doc Comment
 *
 * @category Class
 * @description Field type. Possible values:  – **string** field with the “Text” type  – **integer** field with the “Number”  type  – **datetime** field with the “Date and time” type
 * @package  BSG\Api\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ContactFieldType
{
    /**
     * Possible values of this enum
     */
    public const TEXT = 'text';

    public const DATE = 'date';

    public const NUMBER = 'number';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::TEXT,
            self::DATE,
            self::NUMBER
        ];
    }
}


