<?php
/**
 * OtpTemplateStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BSG\Api\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * One-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BSG\Api\V2\Model;
use \BSG\Api\V2\ObjectSerializer;

/**
 * OtpTemplateStatus Class Doc Comment
 *
 * @category Class
 * @description Status of the template. After template creation, the status of the template will always be “requested.”
 * @package  BSG\Api\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OtpTemplateStatus
{
    /**
     * Possible values of this enum
     */
    public const REQUESTED = 'requested';

    public const APPROVED = 'approved';

    public const REJECTED = 'rejected';

    public const DELETED = 'deleted';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::REQUESTED,
            self::APPROVED,
            self::REJECTED,
            self::DELETED
        ];
    }
}


