<?php
/**
 * ShortLinkStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BSG\Api\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * One-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BSG\Api\V2\Model;
use \BSG\Api\V2\ObjectSerializer;

/**
 * ShortLinkStatus Class Doc Comment
 *
 * @category Class
 * @description If original link is used at first time it may not pass the moderation automatically. Be careful only link in **active** status can be used for redirect!*
 * @package  BSG\Api\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ShortLinkStatus
{
    /**
     * Possible values of this enum
     */
    public const ACTIVE = 'active';

    public const BLOCKED = 'blocked';

    public const NOT_PAID = 'not_paid';

    public const DELETED = 'deleted';

    public const PROBLEM = 'problem';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ACTIVE,
            self::BLOCKED,
            self::NOT_PAID,
            self::DELETED,
            self::PROBLEM
        ];
    }
}


