<?php
/**
 * ShortUrlLinkSchema
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BSG\Api\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * One-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BSG\Api\V2\Model;

use \ArrayAccess;
use \BSG\Api\V2\ObjectSerializer;

/**
 * ShortUrlLinkSchema Class Doc Comment
 *
 * @category Class
 * @description Short Link object
 * @package  BSG\Api\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ShortUrlLinkSchema implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ShortUrlLinkSchema';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'status' => '\BSG\Api\V2\Model\ShortLinkStatus',
        'name' => 'string',
        'slug' => 'string',
        'campaign_id' => 'int',
        'message_id' => 'int',
        'init_deleted_at' => '\DateTime',
        'created_at' => '\DateTime',
        'short_link' => 'string',
        'original_link' => 'string',
        'can_restore' => 'bool',
        'count_clicks' => 'int',
        'count_human_clicks' => 'int',
        'count_unique_clicks' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'status' => null,
        'name' => null,
        'slug' => null,
        'campaign_id' => null,
        'message_id' => null,
        'init_deleted_at' => 'date-time',
        'created_at' => 'date-time',
        'short_link' => 'url',
        'original_link' => 'url',
        'can_restore' => null,
        'count_clicks' => null,
        'count_human_clicks' => null,
        'count_unique_clicks' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'status' => false,
        'name' => true,
        'slug' => false,
        'campaign_id' => false,
        'message_id' => true,
        'init_deleted_at' => false,
        'created_at' => false,
        'short_link' => false,
        'original_link' => false,
        'can_restore' => false,
        'count_clicks' => false,
        'count_human_clicks' => false,
        'count_unique_clicks' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'status' => 'status',
        'name' => 'name',
        'slug' => 'slug',
        'campaign_id' => 'campaign_id',
        'message_id' => 'message_id',
        'init_deleted_at' => 'init_deleted_at',
        'created_at' => 'created_at',
        'short_link' => 'short_link',
        'original_link' => 'original_link',
        'can_restore' => 'can_restore',
        'count_clicks' => 'count_clicks',
        'count_human_clicks' => 'count_human_clicks',
        'count_unique_clicks' => 'count_unique_clicks'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'status' => 'setStatus',
        'name' => 'setName',
        'slug' => 'setSlug',
        'campaign_id' => 'setCampaignId',
        'message_id' => 'setMessageId',
        'init_deleted_at' => 'setInitDeletedAt',
        'created_at' => 'setCreatedAt',
        'short_link' => 'setShortLink',
        'original_link' => 'setOriginalLink',
        'can_restore' => 'setCanRestore',
        'count_clicks' => 'setCountClicks',
        'count_human_clicks' => 'setCountHumanClicks',
        'count_unique_clicks' => 'setCountUniqueClicks'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'status' => 'getStatus',
        'name' => 'getName',
        'slug' => 'getSlug',
        'campaign_id' => 'getCampaignId',
        'message_id' => 'getMessageId',
        'init_deleted_at' => 'getInitDeletedAt',
        'created_at' => 'getCreatedAt',
        'short_link' => 'getShortLink',
        'original_link' => 'getOriginalLink',
        'can_restore' => 'getCanRestore',
        'count_clicks' => 'getCountClicks',
        'count_human_clicks' => 'getCountHumanClicks',
        'count_unique_clicks' => 'getCountUniqueClicks'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('slug', $data ?? [], null);
        $this->setIfExists('campaign_id', $data ?? [], null);
        $this->setIfExists('message_id', $data ?? [], null);
        $this->setIfExists('init_deleted_at', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('short_link', $data ?? [], null);
        $this->setIfExists('original_link', $data ?? [], null);
        $this->setIfExists('can_restore', $data ?? [], true);
        $this->setIfExists('count_clicks', $data ?? [], null);
        $this->setIfExists('count_human_clicks', $data ?? [], null);
        $this->setIfExists('count_unique_clicks', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['name']) && (mb_strlen($this->container['name']) > 50)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['name']) && (mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['slug']) && (mb_strlen($this->container['slug']) > 25)) {
            $invalidProperties[] = "invalid value for 'slug', the character length must be smaller than or equal to 25.";
        }

        if (!is_null($this->container['slug']) && (mb_strlen($this->container['slug']) < 1)) {
            $invalidProperties[] = "invalid value for 'slug', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['original_link']) && (mb_strlen($this->container['original_link']) > 2048)) {
            $invalidProperties[] = "invalid value for 'original_link', the character length must be smaller than or equal to 2048.";
        }

        if (!is_null($this->container['original_link']) && (mb_strlen($this->container['original_link']) < 1)) {
            $invalidProperties[] = "invalid value for 'original_link', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id short link unique id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \BSG\Api\V2\Model\ShortLinkStatus|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \BSG\Api\V2\Model\ShortLinkStatus|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Name of short link. like a comment
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($name) && (mb_strlen($name) > 50)) {
            throw new \InvalidArgumentException('invalid length for $name when calling ShortUrlLinkSchema., must be smaller than or equal to 50.');
        }
        if (!is_null($name) && (mb_strlen($name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $name when calling ShortUrlLinkSchema., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets slug
     *
     * @return string|null
     */
    public function getSlug()
    {
        return $this->container['slug'];
    }

    /**
     * Sets slug
     *
     * @param string|null $slug part of short link after domain
     *
     * @return self
     */
    public function setSlug($slug)
    {
        if (is_null($slug)) {
            throw new \InvalidArgumentException('non-nullable slug cannot be null');
        }
        if ((mb_strlen($slug) > 25)) {
            throw new \InvalidArgumentException('invalid length for $slug when calling ShortUrlLinkSchema., must be smaller than or equal to 25.');
        }
        if ((mb_strlen($slug) < 1)) {
            throw new \InvalidArgumentException('invalid length for $slug when calling ShortUrlLinkSchema., must be bigger than or equal to 1.');
        }

        $this->container['slug'] = $slug;

        return $this;
    }

    /**
     * Gets campaign_id
     *
     * @return int|null
     */
    public function getCampaignId()
    {
        return $this->container['campaign_id'];
    }

    /**
     * Sets campaign_id
     *
     * @param int|null $campaign_id campaign ID if short link is part of sms campaign.  Campaign allow send messages to all the leads with different short link for each lead that follows to the same original link
     *
     * @return self
     */
    public function setCampaignId($campaign_id)
    {
        if (is_null($campaign_id)) {
            throw new \InvalidArgumentException('non-nullable campaign_id cannot be null');
        }
        $this->container['campaign_id'] = $campaign_id;

        return $this;
    }

    /**
     * Gets message_id
     *
     * @return int|null
     */
    public function getMessageId()
    {
        return $this->container['message_id'];
    }

    /**
     * Sets message_id
     *
     * @param int|null $message_id message id for short links created as part of [sms campaign](#tag/Campaign-SMS)
     *
     * @return self
     */
    public function setMessageId($message_id)
    {
        if (is_null($message_id)) {
            array_push($this->openAPINullablesSetToNull, 'message_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('message_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['message_id'] = $message_id;

        return $this;
    }

    /**
     * Gets init_deleted_at
     *
     * @return \DateTime|null
     */
    public function getInitDeletedAt()
    {
        return $this->container['init_deleted_at'];
    }

    /**
     * Sets init_deleted_at
     *
     * @param \DateTime|null $init_deleted_at Date and time when short link was deactivated
     *
     * @return self
     */
    public function setInitDeletedAt($init_deleted_at)
    {
        if (is_null($init_deleted_at)) {
            throw new \InvalidArgumentException('non-nullable init_deleted_at cannot be null');
        }
        $this->container['init_deleted_at'] = $init_deleted_at;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at Date and time when short link was created
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets short_link
     *
     * @return string|null
     */
    public function getShortLink()
    {
        return $this->container['short_link'];
    }

    /**
     * Sets short_link
     *
     * @param string|null $short_link short link url that can be used to redirect to original link
     *
     * @return self
     */
    public function setShortLink($short_link)
    {
        if (is_null($short_link)) {
            throw new \InvalidArgumentException('non-nullable short_link cannot be null');
        }
        $this->container['short_link'] = $short_link;

        return $this;
    }

    /**
     * Gets original_link
     *
     * @return string|null
     */
    public function getOriginalLink()
    {
        return $this->container['original_link'];
    }

    /**
     * Sets original_link
     *
     * @param string|null $original_link Original link where to short link will redirect
     *
     * @return self
     */
    public function setOriginalLink($original_link)
    {
        if (is_null($original_link)) {
            throw new \InvalidArgumentException('non-nullable original_link cannot be null');
        }
        if ((mb_strlen($original_link) > 2048)) {
            throw new \InvalidArgumentException('invalid length for $original_link when calling ShortUrlLinkSchema., must be smaller than or equal to 2048.');
        }
        if ((mb_strlen($original_link) < 1)) {
            throw new \InvalidArgumentException('invalid length for $original_link when calling ShortUrlLinkSchema., must be bigger than or equal to 1.');
        }

        $this->container['original_link'] = $original_link;

        return $this;
    }

    /**
     * Gets can_restore
     *
     * @return bool|null
     */
    public function getCanRestore()
    {
        return $this->container['can_restore'];
    }

    /**
     * Sets can_restore
     *
     * @param bool|null $can_restore For link marked as deleted it can be restored a few time if can_restore=true
     *
     * @return self
     */
    public function setCanRestore($can_restore)
    {
        if (is_null($can_restore)) {
            throw new \InvalidArgumentException('non-nullable can_restore cannot be null');
        }
        $this->container['can_restore'] = $can_restore;

        return $this;
    }

    /**
     * Gets count_clicks
     *
     * @return int|null
     */
    public function getCountClicks()
    {
        return $this->container['count_clicks'];
    }

    /**
     * Sets count_clicks
     *
     * @param int|null $count_clicks Number of clicks on a short link  *Please note: count of clicks updated with some latency*
     *
     * @return self
     */
    public function setCountClicks($count_clicks)
    {
        if (is_null($count_clicks)) {
            throw new \InvalidArgumentException('non-nullable count_clicks cannot be null');
        }
        $this->container['count_clicks'] = $count_clicks;

        return $this;
    }

    /**
     * Gets count_human_clicks
     *
     * @return int|null
     */
    public function getCountHumanClicks()
    {
        return $this->container['count_human_clicks'];
    }

    /**
     * Sets count_human_clicks
     *
     * @param int|null $count_human_clicks Number of clicks on a short link looks like human  We use some heuristics to determine is it real human or looks like bot
     *
     * @return self
     */
    public function setCountHumanClicks($count_human_clicks)
    {
        if (is_null($count_human_clicks)) {
            throw new \InvalidArgumentException('non-nullable count_human_clicks cannot be null');
        }
        $this->container['count_human_clicks'] = $count_human_clicks;

        return $this;
    }

    /**
     * Gets count_unique_clicks
     *
     * @return int|null
     */
    public function getCountUniqueClicks()
    {
        return $this->container['count_unique_clicks'];
    }

    /**
     * Sets count_unique_clicks
     *
     * @param int|null $count_unique_clicks Number of unique clicks on a short link  We use combination of ip address user-agent cookies and so on to account the same user just once
     *
     * @return self
     */
    public function setCountUniqueClicks($count_unique_clicks)
    {
        if (is_null($count_unique_clicks)) {
            throw new \InvalidArgumentException('non-nullable count_unique_clicks cannot be null');
        }
        $this->container['count_unique_clicks'] = $count_unique_clicks;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


