<?php
/**
 * StatisticsData
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BSG\Api\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * One-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BSG\Api\V2\Model;

use \ArrayAccess;
use \BSG\Api\V2\ObjectSerializer;

/**
 * StatisticsData Class Doc Comment
 *
 * @category Class
 * @package  BSG\Api\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class StatisticsData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'StatisticsData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'delivered' => 'int',
        'sent' => 'int',
        'scheduled' => 'int',
        'moderation' => 'int',
        'accepted' => 'int',
        'sending' => 'int',
        'expired' => 'int',
        'failed' => 'int',
        'undelivered' => 'int',
        'unknown' => 'int',
        'read' => 'int',
        'not_viber_user' => 'int',
        'not_rcs_user' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'delivered' => null,
        'sent' => null,
        'scheduled' => null,
        'moderation' => null,
        'accepted' => null,
        'sending' => null,
        'expired' => null,
        'failed' => null,
        'undelivered' => null,
        'unknown' => null,
        'read' => null,
        'not_viber_user' => null,
        'not_rcs_user' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'delivered' => false,
        'sent' => false,
        'scheduled' => false,
        'moderation' => false,
        'accepted' => false,
        'sending' => false,
        'expired' => false,
        'failed' => false,
        'undelivered' => false,
        'unknown' => false,
        'read' => false,
        'not_viber_user' => false,
        'not_rcs_user' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'delivered' => 'delivered',
        'sent' => 'sent',
        'scheduled' => 'scheduled',
        'moderation' => 'moderation',
        'accepted' => 'accepted',
        'sending' => 'sending',
        'expired' => 'expired',
        'failed' => 'failed',
        'undelivered' => 'undelivered',
        'unknown' => 'unknown',
        'read' => 'read',
        'not_viber_user' => 'not_viber_user',
        'not_rcs_user' => 'not_rcs_user'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'delivered' => 'setDelivered',
        'sent' => 'setSent',
        'scheduled' => 'setScheduled',
        'moderation' => 'setModeration',
        'accepted' => 'setAccepted',
        'sending' => 'setSending',
        'expired' => 'setExpired',
        'failed' => 'setFailed',
        'undelivered' => 'setUndelivered',
        'unknown' => 'setUnknown',
        'read' => 'setRead',
        'not_viber_user' => 'setNotViberUser',
        'not_rcs_user' => 'setNotRcsUser'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'delivered' => 'getDelivered',
        'sent' => 'getSent',
        'scheduled' => 'getScheduled',
        'moderation' => 'getModeration',
        'accepted' => 'getAccepted',
        'sending' => 'getSending',
        'expired' => 'getExpired',
        'failed' => 'getFailed',
        'undelivered' => 'getUndelivered',
        'unknown' => 'getUnknown',
        'read' => 'getRead',
        'not_viber_user' => 'getNotViberUser',
        'not_rcs_user' => 'getNotRcsUser'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('delivered', $data ?? [], null);
        $this->setIfExists('sent', $data ?? [], null);
        $this->setIfExists('scheduled', $data ?? [], null);
        $this->setIfExists('moderation', $data ?? [], null);
        $this->setIfExists('accepted', $data ?? [], null);
        $this->setIfExists('sending', $data ?? [], null);
        $this->setIfExists('expired', $data ?? [], null);
        $this->setIfExists('failed', $data ?? [], null);
        $this->setIfExists('undelivered', $data ?? [], null);
        $this->setIfExists('unknown', $data ?? [], null);
        $this->setIfExists('read', $data ?? [], null);
        $this->setIfExists('not_viber_user', $data ?? [], null);
        $this->setIfExists('not_rcs_user', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets delivered
     *
     * @return int|null
     */
    public function getDelivered()
    {
        return $this->container['delivered'];
    }

    /**
     * Sets delivered
     *
     * @param int|null $delivered delivered
     *
     * @return self
     */
    public function setDelivered($delivered)
    {
        if (is_null($delivered)) {
            throw new \InvalidArgumentException('non-nullable delivered cannot be null');
        }
        $this->container['delivered'] = $delivered;

        return $this;
    }

    /**
     * Gets sent
     *
     * @return int|null
     */
    public function getSent()
    {
        return $this->container['sent'];
    }

    /**
     * Sets sent
     *
     * @param int|null $sent sent
     *
     * @return self
     */
    public function setSent($sent)
    {
        if (is_null($sent)) {
            throw new \InvalidArgumentException('non-nullable sent cannot be null');
        }
        $this->container['sent'] = $sent;

        return $this;
    }

    /**
     * Gets scheduled
     *
     * @return int|null
     */
    public function getScheduled()
    {
        return $this->container['scheduled'];
    }

    /**
     * Sets scheduled
     *
     * @param int|null $scheduled scheduled
     *
     * @return self
     */
    public function setScheduled($scheduled)
    {
        if (is_null($scheduled)) {
            throw new \InvalidArgumentException('non-nullable scheduled cannot be null');
        }
        $this->container['scheduled'] = $scheduled;

        return $this;
    }

    /**
     * Gets moderation
     *
     * @return int|null
     */
    public function getModeration()
    {
        return $this->container['moderation'];
    }

    /**
     * Sets moderation
     *
     * @param int|null $moderation moderation
     *
     * @return self
     */
    public function setModeration($moderation)
    {
        if (is_null($moderation)) {
            throw new \InvalidArgumentException('non-nullable moderation cannot be null');
        }
        $this->container['moderation'] = $moderation;

        return $this;
    }

    /**
     * Gets accepted
     *
     * @return int|null
     */
    public function getAccepted()
    {
        return $this->container['accepted'];
    }

    /**
     * Sets accepted
     *
     * @param int|null $accepted accepted
     *
     * @return self
     */
    public function setAccepted($accepted)
    {
        if (is_null($accepted)) {
            throw new \InvalidArgumentException('non-nullable accepted cannot be null');
        }
        $this->container['accepted'] = $accepted;

        return $this;
    }

    /**
     * Gets sending
     *
     * @return int|null
     */
    public function getSending()
    {
        return $this->container['sending'];
    }

    /**
     * Sets sending
     *
     * @param int|null $sending sending
     *
     * @return self
     */
    public function setSending($sending)
    {
        if (is_null($sending)) {
            throw new \InvalidArgumentException('non-nullable sending cannot be null');
        }
        $this->container['sending'] = $sending;

        return $this;
    }

    /**
     * Gets expired
     *
     * @return int|null
     */
    public function getExpired()
    {
        return $this->container['expired'];
    }

    /**
     * Sets expired
     *
     * @param int|null $expired expired
     *
     * @return self
     */
    public function setExpired($expired)
    {
        if (is_null($expired)) {
            throw new \InvalidArgumentException('non-nullable expired cannot be null');
        }
        $this->container['expired'] = $expired;

        return $this;
    }

    /**
     * Gets failed
     *
     * @return int|null
     */
    public function getFailed()
    {
        return $this->container['failed'];
    }

    /**
     * Sets failed
     *
     * @param int|null $failed failed
     *
     * @return self
     */
    public function setFailed($failed)
    {
        if (is_null($failed)) {
            throw new \InvalidArgumentException('non-nullable failed cannot be null');
        }
        $this->container['failed'] = $failed;

        return $this;
    }

    /**
     * Gets undelivered
     *
     * @return int|null
     */
    public function getUndelivered()
    {
        return $this->container['undelivered'];
    }

    /**
     * Sets undelivered
     *
     * @param int|null $undelivered undelivered
     *
     * @return self
     */
    public function setUndelivered($undelivered)
    {
        if (is_null($undelivered)) {
            throw new \InvalidArgumentException('non-nullable undelivered cannot be null');
        }
        $this->container['undelivered'] = $undelivered;

        return $this;
    }

    /**
     * Gets unknown
     *
     * @return int|null
     */
    public function getUnknown()
    {
        return $this->container['unknown'];
    }

    /**
     * Sets unknown
     *
     * @param int|null $unknown unknown
     *
     * @return self
     */
    public function setUnknown($unknown)
    {
        if (is_null($unknown)) {
            throw new \InvalidArgumentException('non-nullable unknown cannot be null');
        }
        $this->container['unknown'] = $unknown;

        return $this;
    }

    /**
     * Gets read
     *
     * @return int|null
     */
    public function getRead()
    {
        return $this->container['read'];
    }

    /**
     * Sets read
     *
     * @param int|null $read read
     *
     * @return self
     */
    public function setRead($read)
    {
        if (is_null($read)) {
            throw new \InvalidArgumentException('non-nullable read cannot be null');
        }
        $this->container['read'] = $read;

        return $this;
    }

    /**
     * Gets not_viber_user
     *
     * @return int|null
     */
    public function getNotViberUser()
    {
        return $this->container['not_viber_user'];
    }

    /**
     * Sets not_viber_user
     *
     * @param int|null $not_viber_user not_viber_user
     *
     * @return self
     */
    public function setNotViberUser($not_viber_user)
    {
        if (is_null($not_viber_user)) {
            throw new \InvalidArgumentException('non-nullable not_viber_user cannot be null');
        }
        $this->container['not_viber_user'] = $not_viber_user;

        return $this;
    }

    /**
     * Gets not_rcs_user
     *
     * @return int|null
     */
    public function getNotRcsUser()
    {
        return $this->container['not_rcs_user'];
    }

    /**
     * Sets not_rcs_user
     *
     * @param int|null $not_rcs_user not_rcs_user
     *
     * @return self
     */
    public function setNotRcsUser($not_rcs_user)
    {
        if (is_null($not_rcs_user)) {
            throw new \InvalidArgumentException('non-nullable not_rcs_user cannot be null');
        }
        $this->container['not_rcs_user'] = $not_rcs_user;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


